apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-bicycle-rental-database-ns-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/local-bicycle-rental-database-ns"