apiVersion: v1
kind: PersistentVolume
metadata:
  name: central-bicycle-rental-database-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/central-bicycle-rental-database"
