name: Build and Push Docker Images

on:
  push:
    branches:
      - '**'

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      
      - name: Build and push central-bicycle-rental image
        uses: docker/build-push-action@v4
        with:
          context: ./central-bicycle-rental
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/central-bicycle-rental:latest

      - name: Build and push local-bicycle-rental image
        uses: docker/build-push-action@v4
        with:
          context: ./local-bicycle-rental
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/local-bicycle-rental:latest
